SELECT * FROM customer;

--Q1 What is the total revenue generated by male vs female customer?
SELECT gender,SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

--Q2 Which Customer used a discount but still spent more than the avg purchased amount
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied='Yes' AND 
	purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

--Q3 Which are the top 5 product with the highest avg review rating
SELECT item_purchased,ROUND(AVG(review_rating::numeric),2) AS AVG_RATING
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC LIMIT 5;

--Q4 Comparethe avg purchase amount between standard and express shipping
SELECT shipping_type,ROUND(AVG(purchase_amount),2) AS AVG_AMOUNT
FROM customer
GROUP BY shipping_type
HAVING shipping_type IN ('Standard','Express');

--Q5 Do subscribe customer spend more? compare avg spend and totalrevenue between 
--subscribers and non-subscriber
SELECT subscription_status,COUNT(customer_id),
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend,total_revenue DESC;

--Q6 Which 5 product have highest percentage of purcahse with discount applied
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)*100/COUNT(*),2)AS discounrate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7 Segment customer into New,Returning and Loyal based on their total number of previous 
--purchased and show count of each segment
WITH customer_type AS (
SELECT customer_id,previous_purchases,
CASE 
	WHEN previous_purchases =1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
END AS customer_segment
FROM customer
)

SELECT customer_segment,COUNT(*) AS number_of_customer 
FROM customer_type
GROUP BY customer_segment;

--Q8 What are top 3 most purchased product within each category
WITH item_count AS (
SELECT category,item_purchased,
COUNT(customer_id) AS total_purchased,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category,item_purchased
)

SELECT item_rank,category,item_purchased,total_purchased
FROM item_count
WHERE item_rank <=3;

SELECT * FROM customer;

--Q9 Are customer who are repeat buyers(more than 5 previous purchased)
--also likely to subscribe?
SELECT subscription_status,COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10 What is the revenue contribution of each age group
SELECT age_group,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC ;